updated the code build image to standard 3.0 as per jira Her-425
globeandmail/aws-codebuild-project pull request #5
Opened 2021-07-16 17:02 UTC by sindhesaikiran

2021-07-16 17:37 UTC, lishanguoglobemail approved these changes

2021-09-24 12:54 UTC, tgam-smickeler requested changes
The default value for `codebuild_image` can be updated once adequate testing has been performed to ensure it won't break existing deployments.

2021-09-24 12:54 UTC, tgam-smickeler commented on variables.tf
> +  default     = "aws/codebuild/standard:3.0"
Before changing the default image, it must be tested to ensure compatibility with existing deployments..

2021-09-24 13:11 UTC, lishanguoglobemail commented
The latest tag version is 1.7 now. Git base off master branch and then tag this version with 1.8.

2022-05-10 12:51 UTC, closed without merging